# Site settings
title: Lucas Jandrey
SEOTitle: Lucas Jandrey | Blog
header-img: img/home-bg.jpg
email: lucas@jandrey.dev
description: "Assuntos que eu vou trazer em alguma conversa de bar ou em uma reunião empresarial"
keyword: "Programação, Tecnologia, Filosofia, Sociologia, Videogames, Séries, Filmes"
url: "https://jandrey.dev" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: jandr3y
twitter_username: jandr3y
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: lucas-jandrey

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-YBRQKJ6YXS" # Format: UA-xxxxxx-xx
ga_domain: jandrey.dev

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Software Engineer <br> Logcomex"
sidebar-avatar: https://github.com/jandr3y.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value
tags:
  - poemas

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: false
