# Site settings
site: Ephesus
title: Lucas Jandrey
keywords: personal, blog, tecnologia, tech, developer
description: >-
  Tecnologia e Chapasao
lang: pt-BR
timezone:  Sao_Paulo/Brasil
#repo: https://github.com/onepase/Ephesus # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
#google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code

# Author settings
author:
  name: Lucas Jandrey
  bio: Software Developer/Tech Lead<br>Curitiba, PR<br>PHP | TypeScript | SQL
  picture: assets/images/profile.jpeg 
  github: jandr3y # github username
  twitter: jandr3y # twitter username
  instagram: luacks # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: luacks # linkedin username
  email: lucas@jandrey.dev # email adress


# URL settings
url: "https://jandrey.dev" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false